apiVersion: v1
kind: Service
metadata:
  name: payment-ms-service
spec:
  type: LoadBalancer
  selector:
    app: payment-ms
  ports:
    - protocol: TCP
      port: 8082          # External port exposed by LoadBalancer
      targetPort: 8082    # Port on the container