apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-ms-deployment
  labels:
    app: delivery-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-ms
  template:
    metadata:
      labels:
        app: delivery-ms
    spec:
      containers:
      - name: delivery-ms-container
        image: jeremiahjava55/delivery-ms:latest
        ports:
        - containerPort: 8083
        
        # Optional resource limits
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
