apiVersion: v1
kind: Service
metadata:
  name: delivery-ms-service
spec:
  type: LoadBalancer
  selector:
    app: delivery-ms
  ports:
    - protocol: TCP
      port: 8083          # External port exposed by LoadBalancer
      targetPort: 8083    # Port on the container