apiVersion: v1
kind: Service
metadata:
  name: order-ms-service
spec:
  type: LoadBalancer
  selector:
    app: order-ms
  ports:
    - protocol: TCP
      port: 8084          # External port exposed by LoadBalancer
      targetPort: 8084    # Port on the container